### ISSUE TITLE
Check api handler on https://www.freetogame.com/ 

### ISSUE THREAD

**Issue by MaikovskiyS** [releaseband/golang-integration-developer-test#2]
Hello mates.
-------
Cant get info from site by parametr mobile.
https://www.freetogame.com/api/games?platform=mobile  

  
  
![image](https://github.com/releaseband/golang-integration-developer-test/assets/110031370/d3a919bb-84a2-4c26-abb3-4c4c0c77a1f6)

**Comment by ArmanKoke** [comment]
for this example platform = pc is enough
